from selenium.webdriver.common.by import By

class Locators:
    SEARCH_INPUT = (By.XPATH, "//textarea[@aria-label='Найти']")
    SEARCH_BUTTON = (By.XPATH, "//input[@aria-label='Поиск в Google']")
    SEARCH_FIELD = (By.XPATH, "//h3[1]")
    LOGIN_BUTTON = (By.XPATH, "//div[text()='Вход']")
    EMAIL_INPUT = (By.XPATH, "//input[@placeholder='Ник или e-mail']")
    PASSWORD_INPUT = (By.XPATH, "//input[@placeholder='Пароль']")
    SUBMIT_BUTTON = (By.XPATH, "//button[@type='submit']")
    CHAT_BUTTON = (By.CLASS_NAME, "//a[@class='b-top-profile__message']")
    PHONE_BUTTON = (By.XPATH, "//a//span[text()='Смартфоны']")
    PHONE_FIELD = (By.XPATH, "//h1[contains(text(), 'Мобильные телефоны')]")
    COMPARE_CHECKBOX = (By.XPATH, "//label[@title='К сравнению']")
    COMPARE_CHECKBOX_CHECK  = (By.XPATH, "//label[@title='В сравнении']")
    COMPARE_BUTTON = (By.XPATH, "//a[contains(text(), '2 товара в сравнении')]")
    MIN_PRICE_INPUT = (By.XPATH, "//input[@placeholder='от']")
    MAX_PRICE_INPUT = (By.XPATH, "//input[@placeholder='до']")
    MIN_SCREEN_SELECT = (By.XPATH, "//div[text()='Разрешение экрана']//select[@class='input-style__real']")
    MAX_SCREEN_SELECT = (By.XPATH, "//div[text()='Разрешение экрана']//select[@class='input-style__real']")
    FIRST_ITEM = (By.XPATH, "//a[contains(text(), 'Смартфон HONOR X9c 8GB/256GB титановый фиолетовый)')]")
    OPTIONS_PHONE_1 = (By.XPATH, "//div[contains(text(), 'Android']")
    OPTIONS_PHONE_2 = (By.XPATH, "//div[contains(text(), 'экран 6.78 AMOLED 1224x2700']")
    OPTIONS_PHONE_3 = (By.XPATH, "//div[contains(text(), 'Qualcomm Snapdragon 6 Gen 1')]")
    OPTIONS_PHONE_4 = (By.XPATH, "//div[contains(text(), 'ОЗУ 8 ГБ']")
    ALL_OPTIONS_PHONE = (By.XPATH, "//div[@class='offers-description__specs']/p")
    NAME_ITEM_1 = (By.XPATH, "//span[text()='Смартфон HONOR X9c 8GB/256GB (титановый фиолетовый)']")
    NAME_ITEM_2  = (By.XPATH, "//span[text()='Смартфон Xiaomi Redmi Note 13 8GB/256GB с NFC международная версия (мятно-зеленый)']")
    ADD_ITEM_BASKET = (By.XPATH, "//a[@data-position-id='936:4688180001' and contains(text(), 'В корзину')]")
    SUCCESSFUL_MESSAGE = (By.XPATH, "//div[contains(text(), 'Товар добавлен в корзину')]")
